# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - avans-programmeren-4

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: npm install, build, and test
              run: |
                  npm install

            - name: Zip artifact for deployment
              run: zip release.zip ./* -r

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: release.zip

    integrationtests:
        runs-on: ubuntu-latest
        needs: build
        env:
            MYSQL_ROOT_PASSWORD: root # default root password to use must be 'root'
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_DATABASE: share_a_meal
            DB_USER: root
            DB_PASSWORD: root
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for tests
              run: unzip release.zip

            - name: Start MySQL connection from host
              run: |
                  sudo /etc/init.d/mysql start
                  sudo apt-get install -y mysql-client
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE ${{env.DB_DATABASE}};"

            - name: Import the database
              run: |
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} < share-a-meal.sql
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} -e "SHOW TABLES;"

            - name: npm test
              run: |
                  npm test -- --DB_PASSWORD $MYSQL_ROOT_PASSWORD --DB_USER root --DB_NAME $DB_DATABASE --DB_PORT $DB_PORT

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      permissions:
        id-token: write #This is required for requesting the JWT
  
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: node-app
  
        - name: Unzip artifact for deployment
          run: unzip release.zip
        
        - name: Login to Azure
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CFC2FE75EF344FF488F086891E05324A }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C0E292A5C33245B6B8D57548D3B4AA1E }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_17AD63EC935349C68CE9ECE0FA9085F3 }}
  
        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'Nodejs-express-server'
            slot-name: 'Production'
            package: .